# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "terms", :force => true do |t|
    t.column "term", :string, :limit => 10, :default => "", :null => false
    t.column "year", :integer, :default => 0, :null => false
    t.column "semester", :string, :limit => 15, :default => "", :null => false
    t.column "current", :boolean, :default => false
    t.column "open", :boolean, :default => true
  end

  create_table "users", :force => true do |t|
    t.column "uniqueid", :string, :limit => 15, :default => "", :null => false
    t.column "password", :string
    t.column "preferred_name", :string
    t.column "first_name", :string, :default => "", :null => false
    t.column "middle_name", :string
    t.column "last_name", :string, :default => "", :null => false
    t.column "instructor", :string, :limit => 1, :default => "", :null => false
    t.column "admin", :string, :limit => 1, :default => "N", :null => false
    t.column "affiliation", :string
    t.column "personal_title", :string
    t.column "office_hours", :string
    t.column "phone_number", :string
    t.column "email", :string, :default => "", :null => false
  end

end
