class CreateAutocompletes < ActiveRecord::Migration
  def self.up
    create_table :autocompletes do |t|
      t.column :category, :string, :null => false
      t.column :value, :string, :null => false
      t.timestamps
    end
    add_index(:autocompletes, [:category])
    add_index(:autocompletes, [:category, :value], :unique => true)

    # This default set is the undergraduate major set from the University of Cincinnati, Jan 2013.
    Autocomplete.create :category => 'major', :value => 'Accounting'
    Autocomplete.create :category => 'major', :value => 'Business Economics'
    Autocomplete.create :category => 'major', :value => 'Economics'
    Autocomplete.create :category => 'major', :value => 'Entrepreneurship'
    Autocomplete.create :category => 'major', :value => 'Finance'
    Autocomplete.create :category => 'major', :value => 'Industrial Management'
    Autocomplete.create :category => 'major', :value => 'Information Systems'
    Autocomplete.create :category => 'major', :value => 'International Business'
    Autocomplete.create :category => 'major', :value => 'Marketing'
    Autocomplete.create :category => 'major', :value => 'Operations Management'
    Autocomplete.create :category => 'major', :value => 'Real Estate'
    Autocomplete.create :category => 'major', :value => 'Advanced Medical Imaging Technology'
    Autocomplete.create :category => 'major', :value => 'Communication Sciences and Disorders'
    Autocomplete.create :category => 'major', :value => 'Dietetics'
    Autocomplete.create :category => 'major', :value => 'Food and Nutrition'
    Autocomplete.create :category => 'major', :value => 'Health Information Management Administration'
    Autocomplete.create :category => 'major', :value => 'Health Sciences'
    Autocomplete.create :category => 'major', :value => 'Medical Laboratory Science'
    Autocomplete.create :category => 'major', :value => 'Social Work'
    Autocomplete.create :category => 'major', :value => 'Architecture'
    Autocomplete.create :category => 'major', :value => 'Art History'
    Autocomplete.create :category => 'major', :value => 'Fashion Design'
    Autocomplete.create :category => 'major', :value => 'Fine Arts - Art'
    Autocomplete.create :category => 'major', :value => 'Graphic Communication Design'
    Autocomplete.create :category => 'major', :value => 'Horticulture'
    Autocomplete.create :category => 'major', :value => 'Industrial Design'
    Autocomplete.create :category => 'major', :value => 'Interior Design'
    Autocomplete.create :category => 'major', :value => 'Urban Planning'
    Autocomplete.create :category => 'major', :value => 'Urban Studies'
    Autocomplete.create :category => 'major', :value => 'Athletic Training'
    Autocomplete.create :category => 'major', :value => 'Criminal Justice'
    Autocomplete.create :category => 'major', :value => 'Database Management'
    Autocomplete.create :category => 'major', :value => 'Deaf Studies'
    Autocomplete.create :category => 'major', :value => 'Early Childhood Care & Education'
    Autocomplete.create :category => 'major', :value => 'Early Childhood Education'
    Autocomplete.create :category => 'major', :value => 'Forensic Populations'
    Autocomplete.create :category => 'major', :value => 'Health Education (Exercise & Fitness)'
    Autocomplete.create :category => 'major', :value => 'Health Education (Public & Community Health)'
    Autocomplete.create :category => 'major', :value => 'Information Technology'
    Autocomplete.create :category => 'major', :value => 'Middle School Education Lang Arts & Nat Science'
    Autocomplete.create :category => 'major', :value => 'Middle School Education Lang Arts & Soc Studies'
    Autocomplete.create :category => 'major', :value => 'Middle School Education Language Arts & Mathematic'
    Autocomplete.create :category => 'major', :value => 'Middle School Education Math & Nat Science'
    Autocomplete.create :category => 'major', :value => 'Middle School Education Soc Studies & Math'
    Autocomplete.create :category => 'major', :value => 'Middle School Education Soc Studies & Nat Sci'
    Autocomplete.create :category => 'major', :value => 'Paralegal Studies'
    Autocomplete.create :category => 'major', :value => 'Secondary Education - Chemistry'
    Autocomplete.create :category => 'major', :value => 'Secondary Education - Earth Science'
    Autocomplete.create :category => 'major', :value => 'Secondary Education - Engl Lang Arts'
    Autocomplete.create :category => 'major', :value => 'Secondary Education - Life Sciences'
    Autocomplete.create :category => 'major', :value => 'Secondary Education - Mathematics'
    Autocomplete.create :category => 'major', :value => 'Secondary Education - Physics'
    Autocomplete.create :category => 'major', :value => 'Secondary Education - Social Studies - Geography'
    Autocomplete.create :category => 'major', :value => 'Secondary Education - Social Studies - History'
    Autocomplete.create :category => 'major', :value => 'Secondary Education - Social Studies - Poli Sci'
    Autocomplete.create :category => 'major', :value => 'Signed Language Interpreting'
    Autocomplete.create :category => 'major', :value => 'Special Education - Lang Arts & Mathematics'
    Autocomplete.create :category => 'major', :value => 'Special Education - Lang Arts & Nat Sci'
    Autocomplete.create :category => 'major', :value => 'Sport Administration'
    Autocomplete.create :category => 'major', :value => 'Substance Abuse Counseling'
    Autocomplete.create :category => 'major', :value => 'Violence Prevention in Families, Schools, and Communities'
    Autocomplete.create :category => 'major', :value => 'Aerospace Engineering'
    Autocomplete.create :category => 'major', :value => 'Architectural Engineering'
    Autocomplete.create :category => 'major', :value => 'Biomedical Engineering'
    Autocomplete.create :category => 'major', :value => 'Chemical Engineering'
    Autocomplete.create :category => 'major', :value => 'Civil Engineering'
    Autocomplete.create :category => 'major', :value => 'Computer Engineering'
    Autocomplete.create :category => 'major', :value => 'Computer Science'
    Autocomplete.create :category => 'major', :value => 'Construction Management'
    Autocomplete.create :category => 'major', :value => 'Electrical Engineering'
    Autocomplete.create :category => 'major', :value => 'Electrical Engineering Technology'
    Autocomplete.create :category => 'major', :value => 'Environmental Engineering'
    Autocomplete.create :category => 'major', :value => 'Fire Science'
    Autocomplete.create :category => 'major', :value => 'Mechanical Engineering'
    Autocomplete.create :category => 'major', :value => 'Mechanical Engineering Technology (Bacc)'
    Autocomplete.create :category => 'major', :value => 'Nursing'
    Autocomplete.create :category => 'major', :value => 'RN/BSN'
    Autocomplete.create :category => 'major', :value => 'Ballet'
    Autocomplete.create :category => 'major', :value => 'Bassoon'
    Autocomplete.create :category => 'major', :value => 'Clarinet'
    Autocomplete.create :category => 'major', :value => 'Classical Guitar'
    Autocomplete.create :category => 'major', :value => 'Commercial Music Production'
    Autocomplete.create :category => 'major', :value => 'Composition'
    Autocomplete.create :category => 'major', :value => 'Double Bass'
    Autocomplete.create :category => 'major', :value => 'Drama'
    Autocomplete.create :category => 'major', :value => 'Electronic Media'
    Autocomplete.create :category => 'major', :value => 'Euphonium'
    Autocomplete.create :category => 'major', :value => 'Flute'
    Autocomplete.create :category => 'major', :value => 'French Horn'
    Autocomplete.create :category => 'major', :value => 'Harp'
    Autocomplete.create :category => 'major', :value => 'Harpsichord'
    Autocomplete.create :category => 'major', :value => 'Jazz Studies'
    Autocomplete.create :category => 'major', :value => 'Music'
    Autocomplete.create :category => 'major', :value => 'Music Education'
    Autocomplete.create :category => 'major', :value => 'Music History'
    Autocomplete.create :category => 'major', :value => 'Musical Theater'
    Autocomplete.create :category => 'major', :value => 'Oboe'
    Autocomplete.create :category => 'major', :value => 'Organ'
    Autocomplete.create :category => 'major', :value => 'Percussion'
    Autocomplete.create :category => 'major', :value => 'Piano'
    Autocomplete.create :category => 'major', :value => 'Saxophone'
    Autocomplete.create :category => 'major', :value => 'Theater Design and Production - Costume Design Tech'
    Autocomplete.create :category => 'major', :value => 'Theater Design and Production - Lighting Design Tech'
    Autocomplete.create :category => 'major', :value => 'Theater Design and Production - Sound Design'
    Autocomplete.create :category => 'major', :value => 'Theater Design and Production - Stage Management'
    Autocomplete.create :category => 'major', :value => 'Theater Design and Production - Technical Production'
    Autocomplete.create :category => 'major', :value => 'Trombone'
    Autocomplete.create :category => 'major', :value => 'Trumpet'
    Autocomplete.create :category => 'major', :value => 'Tuba'
    Autocomplete.create :category => 'major', :value => 'Viola'
    Autocomplete.create :category => 'major', :value => 'Violin'
    Autocomplete.create :category => 'major', :value => 'Violoncello'
    Autocomplete.create :category => 'major', :value => 'Voice'
    Autocomplete.create :category => 'major', :value => 'Africana Studies'
    Autocomplete.create :category => 'major', :value => 'Ancient Greek'
    Autocomplete.create :category => 'major', :value => 'Anthropology'
    Autocomplete.create :category => 'major', :value => 'Arabic Language and Culture'
    Autocomplete.create :category => 'major', :value => 'Archaeology (Geoarchaeology)'
    Autocomplete.create :category => 'major', :value => 'Archaeology (Landscape Archaeology)'
    Autocomplete.create :category => 'major', :value => 'Archaeology (Social Complexity)'
    Autocomplete.create :category => 'major', :value => 'Asian Studies'
    Autocomplete.create :category => 'major', :value => 'Biochemistry'
    Autocomplete.create :category => 'major', :value => 'Biological Sciences'
    Autocomplete.create :category => 'major', :value => 'Biological Sciences (Biology of Animals)'
    Autocomplete.create :category => 'major', :value => 'Biological Sciences (Biomedical Studies)'
    Autocomplete.create :category => 'major', :value => 'Biological Sciences (Cell & Molecular Biology)'
    Autocomplete.create :category => 'major', :value => 'Biological Sciences (Ecology & Evolution)'
    Autocomplete.create :category => 'major', :value => 'Business French'
    Autocomplete.create :category => 'major', :value => 'Business Spanish'
    Autocomplete.create :category => 'major', :value => 'Chemistry'
    Autocomplete.create :category => 'major', :value => 'Chinese Languages and Culture'
    Autocomplete.create :category => 'major', :value => 'Classical Civilization'
    Autocomplete.create :category => 'major', :value => 'Classics'
    Autocomplete.create :category => 'major', :value => 'Communication'
    Autocomplete.create :category => 'major', :value => 'Creative Writing'
    Autocomplete.create :category => 'major', :value => 'Critical Visions'
    Autocomplete.create :category => 'major', :value => 'English Literature - Creative Writing'
    Autocomplete.create :category => 'major', :value => 'English Literature - Literary & Cultural Studies'
    Autocomplete.create :category => 'major', :value => 'English Literature - Rhetoric & Professional Writing'
    Autocomplete.create :category => 'major', :value => 'Environmental Analysis & Policy'
    Autocomplete.create :category => 'major', :value => 'Environmental Studies'
    Autocomplete.create :category => 'major', :value => 'European Studies'
    Autocomplete.create :category => 'major', :value => 'Exploratory Undetermined'
    Autocomplete.create :category => 'major', :value => 'Film & Media Studies'
    Autocomplete.create :category => 'major', :value => 'French'
    Autocomplete.create :category => 'major', :value => 'Geographic Information Sciences'
    Autocomplete.create :category => 'major', :value => 'Geography (Environmental Emphasis)'
    Autocomplete.create :category => 'major', :value => 'Geography (GIS Emphasis)'
    Autocomplete.create :category => 'major', :value => 'Geography (Human Emphasis)'
    Autocomplete.create :category => 'major', :value => 'Geography (Remote Sensing)'
    Autocomplete.create :category => 'major', :value => 'Geography (Urban Economic Emphasis)'
    Autocomplete.create :category => 'major', :value => 'Geology'
    Autocomplete.create :category => 'major', :value => 'German Studies'
    Autocomplete.create :category => 'major', :value => 'German-American Studies'
    Autocomplete.create :category => 'major', :value => 'Heritage Studies'
    Autocomplete.create :category => 'major', :value => 'Historic Preservation'
    Autocomplete.create :category => 'major', :value => 'History'
    Autocomplete.create :category => 'major', :value => 'Interdisciplinary'
    Autocomplete.create :category => 'major', :value => 'International Affairs'
    Autocomplete.create :category => 'major', :value => 'International Human Rights'
    Autocomplete.create :category => 'major', :value => 'Italian Language and Culture'
    Autocomplete.create :category => 'major', :value => 'Japanese Language & Culture'
    Autocomplete.create :category => 'major', :value => 'Journalism'
    Autocomplete.create :category => 'major', :value => 'Journalism - Magazine'
    Autocomplete.create :category => 'major', :value => 'Journalism - News'
    Autocomplete.create :category => 'major', :value => 'Journalism - Photojournalism'
    Autocomplete.create :category => 'major', :value => 'Judaic Studies'
    Autocomplete.create :category => 'major', :value => 'Latin American Studies'
    Autocomplete.create :category => 'major', :value => 'Liberal Arts'
    Autocomplete.create :category => 'major', :value => 'Mathematics'
    Autocomplete.create :category => 'major', :value => 'Mathematics (Statistics/Actuarial Sciences)'
    Autocomplete.create :category => 'major', :value => 'Medical Humanities & Bioethics'
    Autocomplete.create :category => 'major', :value => 'Middle Eastern Studies'
    Autocomplete.create :category => 'major', :value => 'Minority Health'
    Autocomplete.create :category => 'major', :value => 'Modern Hebrew'
    Autocomplete.create :category => 'major', :value => 'Neuroscience (Brain, Mind, Behavior)'
    Autocomplete.create :category => 'major', :value => 'Neuroscience (Neurobiology)'
    Autocomplete.create :category => 'major', :value => 'Neuroscience (Neuropsychology)'
    Autocomplete.create :category => 'major', :value => 'Organizational Leadership'
    Autocomplete.create :category => 'major', :value => 'Philosophy'
    Autocomplete.create :category => 'major', :value => 'Physics'
    Autocomplete.create :category => 'major', :value => 'Astrophysics'
    Autocomplete.create :category => 'major', :value => 'Political Science'
    Autocomplete.create :category => 'major', :value => 'Psychology'
    Autocomplete.create :category => 'major', :value => 'Public Relations'
    Autocomplete.create :category => 'major', :value => 'Religious Studies'
    Autocomplete.create :category => 'major', :value => 'Security Studies'
    Autocomplete.create :category => 'major', :value => 'Sociology'
    Autocomplete.create :category => 'major', :value => 'Spanish'
    Autocomplete.create :category => 'major', :value => "Women's Gender & Sexuality Studies"
  end

  def self.down
    drop_table :autocompletes
  end
end
